config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :events, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    post 'attend', on: :member
    delete 'unattend', on: :member
  end

  resources :users, only: [:show] do
    get 'attended_events', on: :member
  end
  
  resources :attendances, only: [:new, :create, :destroy]

  root to: 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :attendances, foreign_key: :attended_event_id
    has_many :attendees, through: :attendances, source: :attendee

    scope :past, -> { where('date < ?', Date.today) }
    scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @past_events = Event.past.order(date: :asc)
    @upcoming_events = Event.upcoming.order(date: :asc)
  end

  def new
    @event = Event.new 
  end

  def create
    @user = current_user
    @event = @user.events.build(events_params)

    if @event.save  
      redirect_to @event, notice: 'Event was succesfully created'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @creator = @event.creator
    @attendees = @event.attendees
  end

  def attend
    @event = Event.find(params[:id])

    if current_user.attended_events.include?(@event)
      redirect_to @event, notice: "You are already attending this event."
    else
      @event.attendees << current_user
      redirect_to @event, notice: "You are now attending the event."
    end
  end

  def unattend
    @event = Event.find(params[:id])

    @event.attendees.delete(current_user)

    redirect_to @event, notice: "You have successfully removed yourself from the event."
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(events_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  
    redirect_to events_path, notice: 'Event was successfully deleted.'
  end

  private

  def events_params
    params.require(:event).permit(:name, :date, :location, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="event-form-container">
  <%= form_with(model: @event, local: true, class: 'event-form') do |form| %>
    <div class="field">
      <%= form.label :name, class: 'label' %>
      <%= form.text_field :name, class: 'input' %>
    </div>

    <div class="field">
      <%= form.label :date, class: 'label' %>
      <%= form.date_field :date, class: 'input' %>
    </div>

    <div class="field">
      <%= form.label :location, class: 'label' %>
      <%= form.text_field :location, class: 'input' %>
    </div>

    <div class="field">
      <%= form.label :description, class: 'label' %>
      <%= form.text_area :description, rows: 4, class: 'textarea' %>
    </div>

    <div class="actions">
      <%= form.submit 'Save Event', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="edit-events-container">
    <h1>Edit Event</h1>

    <%= render 'form', event: @event %>

    <%= link_to 'Back', event_path(@event), class: "btn shared-btn btn-danger"  %>
</div>

app/views/events/index.html.erb
<div class="page">

    <h1>Events</h1>

    <h3>Upcoming Events</h3>
    <ul>
    <% @upcoming_events.each do |event| %>
            <li class="event-container">
                <h2><%= link_to event.name, event_path(event) %></h2>

                <% if user_signed_in? %>
                    <p>Creator: <%= link_to event.creator.first_name, user_path(event.creator) %></p>
                <% end %>  

                <p>Date: <%= event.date.strftime('%A, %B %d, %Y') %></p>
                <p><%= event.location %></p>
            </li>
    <% end %>
    </ul>

    <h3>Past Events<h3>
    <ul>
    <% @past_events.each do |event| %>
            <li class="event-container">
                <h2><%= link_to event.name, event_path(event) %></h2>

                <% if user_signed_in? %>
                    <p>Creator: <%= link_to event.creator.first_name, user_path(event.creator) %></p>
                <% end %>  

                <p>Date: <%= event.date.strftime('%A, %B %d, %Y') %></p>
                <p><%= event.location %></p>
            </li>
    <% end %>
    </ul>
    
</div>

app/views/events/new.html.erb
<div class="new-events-container">
    <h1>Create a new event!</h1>

    <%= render 'events/form' %>
</div>

app/views/events/show.html.erb
<div class="event-show-container">
  <h1> <%= @event.name %></h1>

  <div class="event-details-container">
    <p>Creator: <%= "#{@event.creator.first_name} #{@event.creator.last_name}" %></p>
    <p>Date: <%= @event.date.strftime('%A, %B %d, %Y') %> </p>

    <% if @event.location.present? %>
      <p>Location: <%= @event.location %> </p>
    <% end %>

    <% if @event.description.present? %>
      <p>Description: <%= @event.description %> </p>
    <% end %>
  </div>

  <div class="attendees-section">
    <h2>Attendees</h2>
    <% if @attendees.present? %>
      <ul class="attendees-list">
        <% @attendees.each do |attendee| %>
          <li>
            <span class="attendee-icon"></span>
            <%= link_to "#{attendee.first_name} #{attendee.last_name}", user_path(attendee) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No one is attending this event yet!</p>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <% if current_user.attended_events.include?(@event) %>
      <%= form_with(model: current_user.attendances.find_by(attended_event: @event), local: true, method: :delete) do |form| %>
        <%= form.submit "Unattend Event", class: "btn shared-btn btn-danger" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.attendances.build, url: attendances_path, method: :post) do |form| %>
        <%= form.hidden_field :attended_event_id, value: @event.id %>
        <%= form.submit "Attend Event", class: "btn shared-btn btn-primary" %>
      <% end %>
    <% end %>
  <% else %>
    <p>Please sign in to attend the event.</p>
  <% end %>

  <div class="event-actions">
    <% if @event.creator == current_user %>
      <%= button_to 'Delete Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn shared-btn btn-danger"  %>
      <%= link_to 'Edit Event', edit_event_path(@event), class: 'btn shared-btn btn-primary' %>
    <% end %>
  </div>
</div>