config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :events, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    post 'attend', on: :member
    delete 'unattend', on: :member
  end

  resources :users, only: [:show] do
    get 'attended_events', on: :member
  end
  
  resources :attendances, only: [:new, :create, :destroy]

  root to: 'events#index'
end

app/views/layouts/_attended_events.html.erb
<div id="attended-events-container" class="users-events-container">
  <% if current_user%>
    <h1>Attended Events</h1>

    <div id="userEvents" class="users-attended-events">
      <ul>
        <% current_user.attended_events.each do |event| %>
          <li class="event-item"><%= link_to event.name, event_path(event) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-container">
    <a href="/" class="navbar-brand">Awesome Events</a>
    <div class="navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Post Event", new_event_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link-button" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_users_events.html.erb
<div class="users-events-container">
  <% if current_user %>
    <h1>Hello, <%= current_user.first_name %></h1>
    <button id="toggleEvents" class="custom-button">My Events</button>

    <div id="userEvents" class="users-created-events">
      <ul>
          <% current_user.events.each do |event| %>
          <li class="event-item"><%= link_to event.name, event_path(event) %></li>
          <% end %>
      </ul>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>

  <body>

    <%= render 'layouts/navbar'%>

    <div class="content-container">
      <div class="left-sidebar">
        <%= render 'layouts/users_events'%>
      </div>
      
      <div class="content" id="main-content">
        <%= yield %>
      </div>

      <div class="right-sidebar">
        <%= render 'layouts/attended_events'%>
      </div>
    </div>


  <%= javascript_include_tag('left_sidebar.js') %>
  </body>
</html>